### ISSUE TITLE
Error on Startup of Second Client

### ISSUE THREAD

**Issue by tqkeith** [rosudrag/GameMutexKiller#1]
Ran and accepted the EULA.  Ran the program as admin.

I can get a second launcher up and running.  However, when I hit the play button, I get the error message "Can not startup!  Another instance of "Life is Feudal: MMO" is already running.

I will also point out that the console does say that it killed the lock for the instance.

Any ideas?

**Comment by rosudrag** [comment]
Fixed now in 1.2
